services:
  bitmagnet:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bitmagnet
    volumes:
      - ./data/db:/data/db
      - ./data/bitmagnet:/data/bitmagnet
    ports:
      - "3333:3333"
      - "3334:3334/tcp"
      - "3334:3334/udp"
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=postgres
      - BITMAGNET_POSTGRES=postgres://postgres:postgres@postgres:5432/bitmagnet?sslmode=disable
      - TMDB_API_KEY=${TMDB_API_KEY:-}
      - BITMAGNET_DHT_CRAWLER_BOOTSTRAP_NODES=${BITMAGNET_DHT_CRAWLER_BOOTSTRAP_NODES:-router.utorrent.com:6881,dht.aelitis.com:6881,router.bittorrent.com:6881,dht.transmissionbt.com:6881}
      - LOG_FILE_ROTATOR_ENABLED=true
    depends_on:
      postgres:
        condition: service_healthy
    command:
      - worker
      - run
      - --keys=http_server
      - --keys=queue_server
      - --keys=dht_crawler

  postgres:
    image: postgres:16-alpine
    container_name: bitmagnet-postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    shm_size: 2g
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bitmagnet
      - PGUSER=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      start_period: 20s
